# SPDX-FileCopyrightText: © 2023 Menacit AB <foss@menacit.se>
# SPDX-License-Identifier: CC-BY-SA-4.0
# X-Context: Practical cryptography course - X.509/TLS lab

error_log /dev/stdout;
events {}

http {
  
  log_format custom '$remote_addr - $ssl_client_s_dn - [$time_local] "$request" $status $body_bytes_sent';
  server {
    listen 443 ssl;
    root /input;
    index secret.txt;

    # Enforce TLSv1.2 or higher
    ssl_protocols TLSv1.2 TLSv1.3;

    # cert and key files are mounted to /share in the container
    ssl_certificate /share/sensitive-web-server.example.test.crt;
    ssl_certificate_key /share/sensitive-web-server.example.test.key;

    # Enable mTLS and specify CA cert for client verification
    ssl_verify_client on;
    ssl_client_certificate /share/ca.crt;

    # Enable CRL checking for client certificates
    ssl_crl /share/crl.pem;

    # Log to stdout in a custom format that includes the client certificate CN
    access_log /dev/stdout custom;
    error_log /dev/stdout;
    
  }
}
